package mysqlstore

import (
	"context"
	"database/sql"
	"fmt"
	"net"
	"strings"
	"time"

	driver "github.com/go-sql-driver/mysql"

	"github.com/hanchuanchuan/goinception-plus/internal/backup"
	"github.com/hanchuanchuan/goinception-plus/internal/model"
)

const informationTable = "$_$Inception_backup_information$_$"

type Store struct{ db *sql.DB }

func Open(options backup.TargetOptions) (*Store, error) {
	cfg := driver.NewConfig()
	cfg.Net = "tcp"
	cfg.Addr = net.JoinHostPort(options.Host, fmt.Sprint(options.Port))
	cfg.User = options.User
	cfg.Passwd = options.Password
	cfg.ParseTime = true
	cfg.Timeout = 5 * time.Second
	cfg.ReadTimeout = 15 * time.Second
	cfg.WriteTimeout = 15 * time.Second
	cfg.Params = map[string]string{"charset": "utf8mb4"}
	db, err := sql.Open("mysql", cfg.FormatDSN())
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(4)
	db.SetMaxIdleConns(2)
	return &Store{db: db}, nil
}
func (s *Store) Close() error                   { return s.db.Close() }
func (s *Store) Ping(ctx context.Context) error { return s.db.PingContext(ctx) }
func (s *Store) Save(ctx context.Context, op backup.Operation) (string, error) {
	if len(op.Rollbacks) == 0 {
		op.Rollbacks = []backup.RollbackRecord{{Schema: op.Schema, Table: op.Table}}
	}
	byDB := map[string][]backup.RollbackRecord{}
	for _, r := range op.Rollbacks {
		db := backupDBName(op.Source, r.Schema)
		byDB[db] = append(byDB[db], r)
	}
	var first string
	for db, records := range byDB {
		if first == "" {
			first = db
		}
		if err := s.ensureSchema(ctx, db); err != nil {
			return "", err
		}
		tx, err := s.db.BeginTx(ctx, nil)
		if err != nil {
			return "", err
		}
		if err = s.saveGroup(ctx, tx, db, op, records); err != nil {
			_ = tx.Rollback()
			return "", err
		}
		if err = tx.Commit(); err != nil {
			return "", err
		}
	}
	return first, nil
}
func (s *Store) ensureSchema(ctx context.Context, db string) error {
	if _, err := s.db.ExecContext(ctx, "CREATE DATABASE IF NOT EXISTS "+quote(db)+" DEFAULT CHARACTER SET utf8mb4"); err != nil {
		return err
	}
	info := quote(db) + "." + quote(informationTable)
	_, err := s.db.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS "+info+" (opid_time varchar(50) PRIMARY KEY,start_binlog_file varchar(512),start_binlog_pos int,end_binlog_file varchar(512),end_binlog_pos int,sql_statement mediumtext,host varchar(128),dbname varchar(64),tablename varchar(64),port int,time timestamp,type varchar(20)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
	return err
}
func (s *Store) saveGroup(ctx context.Context, tx *sql.Tx, db string, op backup.Operation, records []backup.RollbackRecord) error {
	// Legacy goInception stores every rollback generated by one statement in
	// the statement's primary backup table. Archery looks up exactly that table
	// through the information row, so splitting a multi-table UPDATE across
	// physical backup tables would hide part of its rollback SQL.
	storageTable := ""
	for _, r := range records {
		if r.Table != "" {
			storageTable = r.Table
			break
		}
	}
	if storageTable != "" {
		table := quote(db) + "." + quote(storageTable)
		if _, err := tx.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS "+table+" (id bigint auto_increment primary key,rollback_statement mediumtext,opid_time varchar(50),KEY idx_opid_time(opid_time)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); err != nil {
			return err
		}
	}
	for _, r := range records {
		if r.SQL != "" {
			if storageTable == "" {
				return fmt.Errorf("rollback record has no primary table")
			}
			if _, err := tx.ExecContext(ctx, "INSERT INTO "+quote(db)+"."+quote(storageTable)+"(rollback_statement,opid_time) VALUES(?,?)", r.SQL, op.OPID); err != nil {
				return err
			}
		}
	}
	first := records[0]
	_, err := tx.ExecContext(ctx, "INSERT INTO "+quote(db)+"."+quote(informationTable)+" VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),?)", op.OPID, op.Start.File, op.Start.Position, op.End.File, op.End.Position, op.Statement.Original, op.Source.Host, first.Schema, first.Table, op.Source.Port, legacyStatementType(op.Statement.Kind))
	return err
}

// legacyStatementType preserves the values written by goInception's
// mysqlExecuteBackupInfoInsertSql.  These strings are part of the backup
// database contract used by existing rollback tooling and Archery.
func legacyStatementType(kind model.StatementKind) string {
	switch kind {
	case model.StatementInsert:
		return "INSERT"
	case model.StatementDelete:
		return "DELETE"
	case model.StatementUpdate:
		return "UPDATE"
	case model.StatementCreateDatabase:
		return "CREATEDB"
	case model.StatementCreateTable:
		return "CREATETABLE"
	case model.StatementAlterTable:
		return "ALTERTABLE"
	case model.StatementDropTable:
		return "DROPTABLE"
	case model.StatementRenameTable:
		return "RENAMETABLE"
	case model.StatementCreateIndex:
		return "CREATEINDEX"
	case model.StatementDropIndex:
		return "DROPINDEX"
	default:
		return "UNKNOWN"
	}
}
func backupDBName(source model.TargetOptions, schema string) string {
	v := fmt.Sprintf("%s_%d_%s", source.Host, source.Port, schema)
	v = strings.NewReplacer("-", "_", ".", "_").Replace(v)
	if len(v) > 64 {
		v = v[len(v)-64:]
	}
	return v
}
func quote(v string) string { return "`" + strings.ReplaceAll(v, "`", "``") + "`" }
